name: travel_planner_api
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  conduit: ^4.0.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.7.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.0.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.0
